---
title: argparse
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

> Parser for command-line options, arguments and sub-commands

*********************************************************************

## links

* https://docs.python.org/3/library/argparse  

realpython:

* https://realpython.com/command-line-interfaces-python-argparse  
* https://realpython.com/comparing-python-command-line-parsing-libraries-argparse-docopt-click  

*********************************************************************

## example

```{r, opts.label="cat_file"}
cat_file('argparse_example.py')
```

```{sh, cache=FALSE}
/usr/local/anaconda3/envs/how2-py/bin/python \
argparse_example.py -h
```

```{sh, cache=FALSE}
/usr/local/anaconda3/envs/how2-py/bin/python \
argparse_example.py -v
```

```{sh, cache=FALSE}
/usr/local/anaconda3/envs/how2-py/bin/python \
argparse_example.py hello world
```

```{sh, cache=FALSE}
/usr/local/anaconda3/envs/how2-py/bin/python \
argparse_example.py hello world -i 99 -t
```