---
title: configparser
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

<!-- ********************************************************************* -->

<!-- > Headline -->

<!-- ********************************************************************* -->

<!-- ## faqs -->

<!-- ********************************************************************* -->

<!-- ## links -->

<!-- ********************************************************************* -->

<!-- ## setup -->

<!-- ```sh -->
<!-- pip install todo -->
<!-- ``` -->

<!-- ```{python} -->
<!-- import todo -->
<!-- todo.__version__ -->
<!-- ``` -->

*********************************************************************

## create

Manually:

```{python, cache=FALSE}
from configparser import ConfigParser
config = ConfigParser()
config["section"] = {"option1": "asdf",
                     "option2": "blah"}
with open("temp.config", 'w') as configfile:
    config.write(configfile)
```

```{r, opts.label="cat_file"}
cat_file("temp.config")
```

Programmatically:

```{python, cache=FALSE}
from configparser import ConfigParser
config = ConfigParser()
config.add_section("section1")
config.set("section1", "option1", "abc")
with open("temp.config", 'w') as configfile:
    config.write(configfile)
```

```{r, opts.label="cat_file"}
cat_file("temp.config")
```

*********************************************************************

## read

```{python, cache=FALSE}
from configparser import ConfigParser
config = ConfigParser()
config.read("temp.config")
config.get('section1', 'option1')
# config.get('section1', 'option3') # fails with NoOptionError
```

Update:

```{python, cache=FALSE}
from configparser import ConfigParser
config = ConfigParser()
config.read("temp.config")
config.set("section1", "option2", "qwerty")
config.add_section("section2")
config.set("section2", "option1", "xyz")
# config.set("section3", "option1", "hello") # fails with NoSectionError
with open("temp.config", 'w') as configfile:
    config.write(configfile)
```

```{r, opts.label="cat_file"}
cat_file("temp.config")
```

*********************************************************************

## query

```{python, cache=FALSE}
from configparser import ConfigParser
config = ConfigParser()
config.read("temp.config")
config.sections()
config.has_section("section1")
config.has_option("section1", "option1")
config.has_option("section3", "option1")
```

*********************************************************************

## appendix: dir

```{python}
from pprint import pprint
import configparser
pprint(dir(configparser.ConfigParser))
```