---
title: logging
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

> Logging facility for Python

<!-- ********************************************************************* -->

<!-- ## faqs -->

*********************************************************************

## links

* https://docs.python.org/3/library/logging  
* https://realpython.com/python-logging  
* https://www.datacamp.com/community/tutorials/logging-in-python  
* https://docs.python-guide.org/writing/logging  


*********************************************************************

## basics

```python
import logging
logging.basicConfig(level=logging.INFO)
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')
```

```
INFO:root:This is an info message
WARNING:root:This is a warning message
ERROR:root:This is an error message
CRITICAL:root:This is a critical message
```

### formating

You can format the messages using the `format` argument in `basicConfig` - see here for more info: https://docs.python.org/3/library/logging.html#logrecord-attributes

e.g. 

`format=' %(levelname)s: %(filename)s: %(funcName)s: %(lineno)s: %(message)s')`

* `filename` - file name portion of `pathname` including the file extension
* `funcName` - name of function containing the logging call
* `levelname` - WARNING, INFO, etc.
* `lineno` - line number in source code where logging call was made
* `message` - logged message
* `module` - name portion of `filename` - i.e. without the file extension
* `name` - name of the logger (bespoke, default is root)
* `pathname` - full path of the source file where logging call was made


*********************************************************************

## exception handling

```python
import logging
logging.basicConfig(level=logging.INFO)
try:
    1 / 0
except Exception as e:
    logging.error("Exception occurred", exc_info=True)
```

```
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ZeroDivisionError: division by zero
```

`logging.exception("Exception occurred")` gives the same result

*********************************************************************

## send logs to multiple places

```{python, cache=FALSE}
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(name)s - %(funcName)s - %(levelname)s - %(message)s')

# create a custom logger
logger = logging.getLogger(__name__)

# add a file handler
file_handler = logging.FileHandler('temp.log', mode='w')
file_handler.setLevel(logging.ERROR)
file_format = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(file_format)
logger.addHandler(file_handler)

# write some logs
logger.debug('This is a debug message')
logger.info('This is an info message')
logger.warning('This is a warning message')
logger.error('This is an error message')
logger.critical('This is a critical message')
```

```{sh, cache=FALSE}
cat temp.log
```

