---
title: matplotlib
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

> A comprehensive library for creating static, animated, and interactive visualizations

*********************************************************************

## faqs

*********************************************************************

## links

* https://matplotlib.org/  
* https://www.aosabook.org/en/matplotlib.html

datacamp tutorials:

* [matplotlib-tutorial-python](https://www.datacamp.com/community/tutorials/matplotlib-tutorial-python)  
* [histograms-matplotlib](https://www.datacamp.com/community/tutorials/histograms-matplotlib)  

*********************************************************************

## setup

```sh
pip install matplotlib
```

```{python}
import matplotlib as mpl
mpl.__version__
```

*********************************************************************

## basics

Architecture:

* scripting layer - `pyplot`  
* artist layer - `Artist`  
* backend layer - `FigureCanvaas`, `Renderer`, `Event`  

### ipython magic

Allow matplotlib plots to be plotted inline in the notebook:

```
%matplotlib inline 
```

Allow modification of figures after they have been rendered:

```
%matplotlib notebook 
```

*********************************************************************

## style

```python
mpl.style.use(['ggplot'])
```

*********************************************************************

## pyplot

```python
import matplotlib.pyplot as plt
```

### scatter

```python
plt.plot(1, 1, 'o')
```

### hist

```python
plt.hist(x)
plt.title(r'Normal distribution with $\mu=0, \sigma=1$')
plt.xlabel('x-axis-label')
plt.ylabel('y-axis-label')
plt.text(x, y, 'label')
plt.savefig('a_histogram.png)
plt.show()
```

### scatter

```python
plt.scatter(x, y)
```

### pcolor

Heat map

```python
plt.pcolor(df_pivot, cmap='Rdbu')
plt.colourbar()
plt.show()
```

### annotate

* https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.annotate

```python
# Annotate arrow
plt.annotate('label',                     
             xy=(32, 70),             # place head of the arrow at point (year 2012 , pop 70)
             xytext=(28, 20),         # place base of the arrow at point (year 2008 , pop 20)
             xycoords='data',         # will use the coordinate system of the object being annotated 
             arrowprops=dict(arrowstyle='->', connectionstyle='arc3', color='blue', lw=2)
            )

# Annotate Text
plt.annotate('2008 - 2011 Financial Crisis', # text to display
             xy=(28, 30),                    # start the text at at point (year 2008 , pop 30)
             rotation=72.5,                  # based on trial and error to match the arrow
             va='bottom',                    # want the text to be vertically 'bottom' aligned
             ha='left',                      # want the text to be horizontally 'left' algned.
            )
```

line of best fit

```python
# plot line of best fit
plt.plot(x, fit[0] * x + fit[1], color='red') # recall that x is the Years
plt.annotate('y={0:.0f} x + {1:.0f}'.format(fit[0], fit[1]), xy=(2000, 150000))
```

### subplots

```python
fig = plt.figure() # create figure

ax0 = fig.add_subplot(1, 2, 1) # add subplot 1 (1 row, 2 columns, first plot)
ax1 = fig.add_subplot(1, 2, 2) # add subplot 2 (1 row, 2 columns, second plot). See tip below**

# Subplot 1: Box plot
df_CI.plot(kind='box', color='blue', vert=False, figsize=(20, 6), ax=ax0) # add to subplot 1
ax0.set_title('Box Plots of Immigrants from China and India (1980 - 2013)')
ax0.set_xlabel('Number of Immigrants')
ax0.set_ylabel('Countries')

# Subplot 2: Line plot
df_CI.plot(kind='line', figsize=(20, 6), ax=ax1) # add to subplot 2
ax1.set_title ('Line Plots of Immigrants from China and India (1980 - 2013)')
ax1.set_ylabel('Number of Immigrants')
ax1.set_xlabel('Years')

plt.show()
```

*********************************************************************

## Artist

### Primitive

* `Line2D`  
* `Rectangle`  
* `Circle`  
* `Text`  

### Composite

* `Axis`  
* `Tick`  
* `Axes` - the most important composite artist because it is where most of the plotting methods are defined - e.g. for creating and manipulating the ticks, axis lines, grid and plot background  
* `Figure` - top-level object that contains and manages all of the elements in a given graphic  

```python
from matplotlib.figure import Figure
fig = Figure()
ax = fig.add_subplot(111) # create an axes artist
# 111 means 1 row, 1 col, cell 1
```

*********************************************************************

## backend_bases

### FigureCanvas

Encompasses the area onto which the figure is drawn

```python
from matplotlib.backend_bases import FigureCanvasAgg as FigureCanvas
canvas = FigureCanvas(fig) # see Figure
```

Agg = anti-green geometry - a high performance library

### Renderer

An instance of the Renderer class that knows how to draw on the FigureCanvas

### Event

Handles user input such as keyboard strokes and mouse clicks

*********************************************************************

## ??

### axis labels 

```python
ax = plt.subplots()

# label names
row_labels = list(df.columns)
col_labels = list(df.index)

# move ticks and labels to the center
ax.set_xticks(np.arange(df.shape[1]) + 0.5, minor=False)
ax.set_yticks(np.arange(df.shape[0]) + 0.5, minor=False)

# insert labels
ax.set_xticklabels(row_labels, minor=False)
ax.set_yticklabels(col_labels, minor=False)

# rotate labels
plt.xticks(rotation=90)
```

### figure size

```python
width = 12
height = 10
plt.figure(figsize=(width, height))
```

*********************************************************************

## plot

```python
def PlotPolly(model, independent_variable, dependent_variabble, Name):
    x_new = np.linspace(15, 55, 100)
    y_new = model(x_new)

    plt.plot(independent_variable, dependent_variabble, '.', x_new, y_new, '-')
    plt.title('Polynomial Fit with Matplotlib for Price ~ Length')
    ax = plt.gca()
    ax.set_facecolor((0.898, 0.898, 0.898))
    fig = plt.gcf()
    plt.xlabel(Name)
    plt.ylabel('Price of Cars')

    plt.show()
    plt.close()
```

*********************************************************************

## appendix: colors

```{python}
import matplotlib as mpl
for name, hex in mpl.colors.cnames.items():
    print(name, hex)
```
    
*********************************************************************


