---
title: numpy
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

******************************************************************************************

> numerical python: provides a high-performance multidimensional array object, fast array-oriented arithmetic operations and flexible broadcasting capabilities

*********************************************************************

## links 

* https://www.numpy.org/  
* https://numpydoc.readthedocs.io/en/latest/format.html

realpython:  

* https://realpython.com/tutorials/numpy/  
* https://realpython.com/numpy-array-programming/  
* https://realpython.com/how-to-use-numpy-arange/  

datacamp tutorials:

* https://www.datacamp.com/community/tutorials/python-numpy-tutorial  

e-books:  

* https://jakevdp.github.io/PythonDataScienceHandbook/  

*********************************************************************

```{python}
import numpy as np
np.__version__
```

*********************************************************************

## creating

* numpy array class
* all elements must be the same type

### create from list

```{python}
import numpy as np
np.array([[1, 2, 3], [4, 5, 6]])
np.arange(6).reshape((2,3))
np.linspace(0, 1, 6).reshape((2,3)) 
```

Note the difference between `np.ndarray` and `np.array()` . The former is a data type, while the latter is a function to make arrays from other data structures.

### create from scratch

```{python}
import numpy as np
np.empty((2,3))
np.zeros((2,3))
np.ones((2,3))
np.full((2,3), 42)
np.empty((2,3))
np.eye(3)
```

#### np.random

```{python}
import numpy as np
np.random.seed(42)
np.random.random((2,3))
np.random.normal(0, 1, (2,3))
np.random.randint(0, 10, (2, 3))
```

*********************************************************************

## attributes

### size, shape and type

```python
x.ndim # number of dimensions
x.shape # size of each dimension
x.size # number of elements
x.dtype # e.g. float64
```

### memory usage

```python
x.itemsize # size (in bytes) of each array element
x.nbytes # total size (in bytes) of the array
x.data # memory address
```

*********************************************************************

## indexing

Similar tostandrd list indexing.

### individual elements

```python
x[0,0] # 1st row, 1st column
x[1,1] # 2nd row, 2nd column
```

### sub-arrays

```{python}
import numpy as np
x = np.array([[ 1., 2., 3.], [ 4., 5., 6.]])
x
x[:2, 1:3]
```

Note that array slices return **views** rather than copies of the array. This is different to list slicing (where slices are copies).

To make a copy use `.copy`

```python
y = x[:2, 1:3].copy()
```

*********************************************************************

## reshaping

### change sizes of dimensions

```{python}
import numpy as np
np.arange(6).reshape((2,3))
np.linspace(0, 1, 6).reshape((2,3)) 
```

### add a dimension

```{python}
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
x
x.shape
x.reshape((2,3))
x[np.newaxis, :].shape
```

### flatten

```{python}
import numpy as np
x = np.array([[ 1., 2., 3.], [ 4., 5., 6.]])
x
x.shape
x.ravel()
x.ravel().shape
```

*********************************************************************

## joining

### 1d

```{python}
import numpy as np
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6])
np.concatenate([x, y])
```

### 2d

```{python}
import numpy as np
x = np.array([[ 1., 2., 3.], [ 4., 5., 6.]])
np.concatenate([x, x])
np.vstack([x, x])
```

```{python}
import numpy as np
x = np.array([[ 1., 2., 3.], [ 4., 5., 6.]])
np.concatenate([x, x], axis=1)
np.hstack([x, x])
```

### 3d

Use `np.concatenate` with `axis=1` or `np.dstack`

*********************************************************************

## splitting

### 1d

```{python}
import numpy as np
x = np.arange(10)
a, b = np.split(x, [5])
a
b
```

```{python}
import numpy as np
x = np.arange(10)
a, b, c = np.split(x, [5, 8])
a
b
c
```

### 2d

```{python}
import numpy as np
x = np.arange(12).reshape((3,4))
a, b = np.hsplit(x, [2])
a
b
```

```{python}
import numpy as np
x = np.arange(12).reshape((3,4))
a, b = np.vsplit(x, [2])
a
b
```

*********************************************************************

## products

```python
a = np.array([[1, 0], [0, 1], [2, 4]])
b = np.array([[4, 1], [2, 2], [1, 3]])

# element-wise (i.e. Hadamard) product
a * b 

# dot product
a @ b.T
np.dot(a, b.T)
np.matmul(a, b.T) # different broadcasting rules to np.dot
```

*********************************************************************

## sequences

```{python}
import numpy as np
np.arange(10) # 0 to 9, step size = 1
np.arange(0, 10, 2) # (from, up-to-not-including, step-size)
np.arange(0., 10., 2.)
np.linspace(0, 8, 5) # (from, up-to-including, length)
```

*********************************************************************

## universal functions

These are vectorized operations (also called `ufuncs`).

### arithmetic

ufunc | e.g. | notes
------------- | ------------- | ----------
np.add | `x + 5` | 
np.subtract | `x - 5` | 
np.negative | `-x` | 
np.multiply | `x * 2` | 
np.divide | `x / 2` | 
np.floor_divide | `x // 2` | 
np.power(x, 2) | `x ** 2` | 
np.mod | `x % 2` | 
np.abs, np.absolute | `abs(x)` | 
np.sin | `np.sin(x)` | 
np.cos | `np.cos(x)` | 
np.tan | `np.tan(x)` | 
np.arcsin | `np.arcsin(x)` | 
np.arccos | `np.arccos(x)` | 
np.arctan | `np.arctan(x)` | 
np.exp | `np.exp(x)` | i.e. e^x
np.exp2 | `2 ** x` | 
np.power(3, x) | `3 ** x` | 
np.log | `np.log(x)` | i.e. ln(x)
np.log2 | `np.log2(x)` | 
np.log10 | `np.log10(x)` | 
np.expm1 | `np.expm1(x)` | i.e. exp(x) - 1
np.log1p | `np.log1p(x)` | i.e. log(1 + x)

`np.expm1` and `np.log1p` are specialized versions that are useful for maintaining precision with very small input - when x is very small, these functions give more precise values than if the raw `np.log` or `np.exp` were used.

There are lots more functions available - see also `scipy.special` for some stats ones.

### out argument

p56 python-data-science-handbook

### aggregates

### outer products

*********************************************************************

## constants

* https://numpy.org/doc/stable/reference/constants.html

```python
np.inf
np.nan
np.pi
np.e
```



