---
title: pyhocon
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

## setup

```sh
conda install -c conda-forge pyhocon
```

*********************************************************************

## read

```{sh, echo=FALSE, cache=FALSE}
touch temp.config
echo 'client = {
  user = adsf
  password = adsf
}

blah = {
  blah = {
    blah = blah
  }
}' > temp.config
```

```{r, opts.label="cat_file", cache=FALSE}
cat_file("temp.config", print_filename = TRUE)
```

```{python}
import pyhocon
config = pyhocon.ConfigFactory.parse_file("temp.config")
type(config)
isinstance(config, dict)
config.get('blah')
config.get('blah', 'blah')
config.get('blah', 'blah').keys()
config.get('blah', 'blah').get('blah')
```

```{sh, echo=FALSE, cache=FALSE}
rm temp.config
```


*********************************************************************

## create

TODO

*********************************************************************

## write

```python
# convert ConfigTree to string
config = pyhocon.HOCONConverter.convert(
    config,
    output_format='hocon',
    indent=2,
    compact=False
)

# write file
with open("temp.config", 'w') as fh:
    fh.write(config)
```

```python
# or save directly?
with open("temp.config", "w+") as fh:
    fd.write(pyhocon.HOCONConverter.to_hocon(config, indent=4))
```

*********************************************************************

## convert

### json

```python
# convert ConfigTree to json string
config = pyhocon.HOCONConverter.to_json(config)
# convert json string to dict
config = json.loads(config)
```

